### ISSUE TITLE
Lighting-App: WiFi SSID/Creds not honored

### ISSUE THREAD

**Issue by tommyjlong** [NabuCasa/matter-example-apps#30]
Using iOS companion App for commissioning (iOS ver: iPadOS Version = 16.1.1). 
Home Assistant 2023.2.3
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest
Here is log output on the chip lighting app versioning:
```
I (349) cpu_start: Project name:     chip-lighting-app
I (355) cpu_start: App version:      v1.0
I (360) cpu_start: Compile time:     Jan 26 2023 00:06:17
I (366) cpu_start: ELF file SHA256:  cd59b3813054e966...
I (372) cpu_start: ESP-IDF:          v4.4.3
```
In short, WiFi SSID and credentials entered into the HA Matter Integration (and received by the Matter Server) are not honored, and the `matter wifi connect "network" "password"` command didn't solve the problem either.  The commissioning kept failing when the WiFi Sta tried to connect to an AP.

What I found was that the WiFi SSID/Creds were supplied from iOS App mobile device based on the WiFi network the mobile device was connected to, and the commissioning was failing because the iOS App was connected to a 5GHz WiFi network that the ESP32 does not support.  Once the iOS device had its WiFi connected to a 2.5GHz network, the ESP32 got connected to the networking and commissioning was able to continue.

**Comment by agners** [comment]
There isn't really something we can do about this from the example app side. Not sure if there is something in the official Matter spec about this. Ideally the commissioner (the iOS app) should look up the vendor id/device and warn the user if the currently connected Wi-Fi is incompatible with the device at hand.
